// Generated by tools/build-pvp-catalog.mjs. Do not edit by hand.
export const PVP_SKILLS = Object.freeze({
  "mage_basic_barrier": {
    "active": {
      "buffPct": 0.3,
      "buffStat": "지능",
      "buffTurns": 4,
      "cooldown": 5,
      "healMaxPct": 0.3,
      "name": "환기",
      "type": "buff"
    },
    "classOnly": "mage",
    "id": "mage_basic_barrier",
    "maxPoints": 1,
    "name": "환기"
  },
  "mage_basic_bolt": {
    "active": {
      "cooldown": 2,
      "multiplier": 1.5,
      "name": "마력탄",
      "type": "damage"
    },
    "classOnly": "mage",
    "id": "mage_basic_bolt",
    "maxPoints": 1,
    "name": "마력탄"
  },
  "mage_basic_element": {
    "classOnly": "mage",
    "executeHp": [
      0,
      3,
      6,
      9,
      12,
      15
    ],
    "id": "mage_basic_element",
    "maxPoints": 5,
    "name": "원소 폭발"
  },
  "mage_basic_mana": {
    "classOnly": "mage",
    "id": "mage_basic_mana",
    "maxPoints": 5,
    "name": "기초 마력 수련"
  },
  "mage_fire_burst_v24": {
    "active": {
      "cooldown": 5,
      "hitMult": 0.9,
      "hits": 3,
      "name": "폭열",
      "type": "damage"
    },
    "classOnly": "mage",
    "id": "mage_fire_burst_v24",
    "maxPoints": 1,
    "name": "폭열",
    "specOnly": "화염"
  },
  "mage_fire_ember_v24": {
    "classOnly": "mage",
    "critDmgBonus": [
      0,
      0.2,
      0.4,
      0.6,
      0.8,
      1
    ],
    "id": "mage_fire_ember_v24",
    "maxPoints": 5,
    "name": "불씨 증폭",
    "specOnly": "화염"
  },
  "mage_fire_focus_v24": {
    "classOnly": "mage",
    "critChanceBonus": [
      0,
      0.1,
      0.2,
      0.3
    ],
    "id": "mage_fire_focus_v24",
    "maxPoints": 3,
    "name": "화염 집중",
    "specOnly": "화염"
  },
  "mage_fire_meteor_v24": {
    "active": {
      "cooldown": 6,
      "hitMult": 1,
      "hits": 4,
      "name": "메테오",
      "type": "damage"
    },
    "classOnly": "mage",
    "id": "mage_fire_meteor_v24",
    "maxPoints": 1,
    "name": "메테오",
    "specOnly": "화염"
  },
  "mage_fireball_v24": {
    "active": {
      "cooldown": 4,
      "hitMult": 1.05,
      "hits": 2,
      "name": "대화염구",
      "type": "damage"
    },
    "classOnly": "mage",
    "id": "mage_fireball_v24",
    "maxPoints": 1,
    "name": "대화염구",
    "specOnly": "화염"
  },
  "mage_frost_armor_v24": {
    "active": {
      "cooldown": 6,
      "name": "서리 갑옷",
      "shieldPct": 1.3,
      "type": "shield"
    },
    "classOnly": "mage",
    "id": "mage_frost_armor_v24",
    "maxPoints": 1,
    "name": "서리 갑옷",
    "specOnly": "냉기"
  },
  "mage_frost_focus_v24": {
    "activeStunChance": [
      0,
      0.07,
      0.21,
      0.35
    ],
    "classOnly": "mage",
    "id": "mage_frost_focus_v24",
    "maxPoints": 3,
    "name": "냉기 집중",
    "specOnly": "냉기"
  },
  "mage_frost_lance_v24": {
    "active": {
      "chillTurns": 1,
      "cooldown": 4,
      "forceChill": true,
      "multiplier": 2.1,
      "name": "빙결 창",
      "type": "damage"
    },
    "classOnly": "mage",
    "id": "mage_frost_lance_v24",
    "maxPoints": 1,
    "name": "빙결 창",
    "specOnly": "냉기"
  },
  "mage_frost_mind_v24": {
    "classOnly": "mage",
    "id": "mage_frost_mind_v24",
    "maxPoints": 5,
    "name": "혹한의 정신",
    "specOnly": "냉기"
  },
  "mage_frost_storm_v24": {
    "active": {
      "chillTurns": 2,
      "cooldown": 6,
      "multiplier": 2.7,
      "name": "빙하 폭풍",
      "type": "damage"
    },
    "classOnly": "mage",
    "id": "mage_frost_storm_v24",
    "maxPoints": 1,
    "name": "빙하 폭풍",
    "specOnly": "냉기"
  },
  "priest_basic_faith": {
    "classOnly": "priest",
    "id": "priest_basic_faith",
    "maxPoints": 3,
    "name": "기초 신앙"
  },
  "priest_basic_life": {
    "classOnly": "priest",
    "id": "priest_basic_life",
    "maxPoints": 5,
    "monsterMissChance": [
      0,
      0.05,
      0.1,
      0.15,
      0.2,
      0.25
    ],
    "name": "신앙의 광채"
  },
  "priest_basic_prayer": {
    "classOnly": "priest",
    "id": "priest_basic_prayer",
    "maxPoints": 3,
    "name": "기도의 방벽",
    "reflectPct": [
      0,
      0.05,
      0.1,
      0.15
    ]
  },
  "priest_basic_smite": {
    "active": {
      "cooldown": 5,
      "healMaxPct": 0.25,
      "multiplier": 1.3,
      "name": "신앙의 일격",
      "type": "damage"
    },
    "classOnly": "priest",
    "id": "priest_basic_smite",
    "maxPoints": 1,
    "name": "신앙의 일격"
  },
  "priest_holy_absorb_v24": {
    "active": {
      "cooldown": 5,
      "healMaxPct": 0.5,
      "name": "빛의 섬광",
      "type": "healAllies"
    },
    "classOnly": "priest",
    "id": "priest_holy_absorb_v24",
    "maxPoints": 1,
    "name": "빛의 섬광",
    "specOnly": "신성"
  },
  "priest_holy_barrier_v24": {
    "active": {
      "cooldown": 6,
      "name": "신성 보호막",
      "shieldPct": 0.7,
      "type": "shield"
    },
    "classOnly": "priest",
    "id": "priest_holy_barrier_v24",
    "maxPoints": 1,
    "name": "신성 보호막",
    "specOnly": "신성"
  },
  "priest_holy_focus_v24": {
    "classOnly": "priest",
    "id": "priest_holy_focus_v24",
    "maxPoints": 5,
    "name": "신성 집중",
    "specOnly": "신성"
  },
  "priest_holy_grace_v24": {
    "classOnly": "priest",
    "healBoost": [
      0,
      0.5,
      1,
      1.5
    ],
    "id": "priest_holy_grace_v24",
    "maxPoints": 3,
    "name": "치유 숙련",
    "specOnly": "신성"
  },
  "priest_holy_judgment_v24": {
    "active": {
      "cooldown": 8,
      "healRate": 0.75,
      "multiplier": 2.3,
      "name": "은총의 심판",
      "type": "damageHeal"
    },
    "classOnly": "priest",
    "id": "priest_holy_judgment_v24",
    "maxPoints": 1,
    "name": "은총의 심판",
    "specOnly": "신성"
  },
  "priest_shadow_focus_v24": {
    "classOnly": "priest",
    "id": "priest_shadow_focus_v24",
    "maxPoints": 5,
    "name": "암흑 집중",
    "shadowLifestealChance": [
      0,
      0.1,
      0.15,
      0.2,
      0.25,
      0.3
    ],
    "specOnly": "암흑"
  },
  "priest_shadow_judgment_v24": {
    "active": {
      "cooldown": 6,
      "healMaxPct": 0.3,
      "multiplier": 2.6,
      "name": "암흑 심판",
      "stacks": 6,
      "type": "shadowDot"
    },
    "classOnly": "priest",
    "id": "priest_shadow_judgment_v24",
    "maxPoints": 1,
    "name": "암흑 심판",
    "specOnly": "암흑"
  },
  "priest_shadow_mark_v24": {
    "active": {
      "cooldown": 5,
      "multiplier": 0,
      "name": "암흑 낙인",
      "stacks": 7,
      "type": "shadowDot"
    },
    "classOnly": "priest",
    "id": "priest_shadow_mark_v24",
    "maxPoints": 1,
    "name": "암흑 낙인",
    "specOnly": "암흑"
  },
  "priest_shadow_seed_v24": {
    "active": {
      "cooldown": 4,
      "multiplier": 1.2,
      "name": "암흑의 씨앗",
      "stacks": 4,
      "type": "shadowDot"
    },
    "classOnly": "priest",
    "id": "priest_shadow_seed_v24",
    "maxPoints": 1,
    "name": "암흑의 씨앗",
    "specOnly": "암흑"
  },
  "priest_shadow_void_v24": {
    "classOnly": "priest",
    "id": "priest_shadow_void_v24",
    "maxPoints": 5,
    "name": "공허 숙련",
    "shadowCritChance": [
      0,
      0.2,
      0.4,
      0.6,
      0.8,
      1
    ],
    "specOnly": "암흑"
  },
  "warrior_basic_blade": {
    "classOnly": "warrior",
    "id": "warrior_basic_blade",
    "maxPoints": 3,
    "name": "기초 검술"
  },
  "warrior_basic_body": {
    "classOnly": "warrior",
    "id": "warrior_basic_body",
    "maxPoints": 3,
    "name": "기초 체력 단련"
  },
  "warrior_basic_guard": {
    "classOnly": "warrior",
    "guardShieldPct": [
      0,
      0.02,
      0.04,
      0.06
    ],
    "id": "warrior_basic_guard",
    "maxPoints": 3,
    "name": "막기 훈련"
  },
  "warrior_basic_strike": {
    "active": {
      "cooldown": 4,
      "ignoreShield": true,
      "multiplier": 1.8,
      "name": "전사의 일격",
      "type": "damage"
    },
    "classOnly": "warrior",
    "id": "warrior_basic_strike",
    "maxPoints": 1,
    "name": "전사의 일격"
  },
  "warrior_def_armor": {
    "armorBonusPct": [
      0,
      0.02,
      0.04,
      0.06,
      0.08,
      0.1
    ],
    "classOnly": "warrior",
    "id": "warrior_def_armor",
    "maxPoints": 5,
    "name": "공세 갑옷",
    "specOnly": "방어"
  },
  "warrior_def_bastion": {
    "classOnly": "warrior",
    "id": "warrior_def_bastion",
    "maxPoints": 1,
    "name": "수호자의 맹세",
    "reviveCooldown": 11,
    "reviveHealPct": 1,
    "specOnly": "방어"
  },
  "warrior_def_resist": {
    "classOnly": "warrior",
    "cleanseChance": [
      0,
      0.2,
      0.4,
      0.6,
      0.8,
      1
    ],
    "id": "warrior_def_resist",
    "maxPoints": 5,
    "name": "불굴의 의지",
    "specOnly": "방어"
  },
  "warrior_def_stance": {
    "active": {
      "cooldown": 6,
      "name": "방어 태세",
      "shieldPct": 0.1,
      "type": "shield"
    },
    "classOnly": "warrior",
    "id": "warrior_def_stance",
    "maxPoints": 1,
    "name": "방어 태세",
    "specOnly": "방어"
  },
  "warrior_def_wall": {
    "active": {
      "cooldown": 7,
      "name": "방패 돌진",
      "shieldPct": 0.1,
      "type": "shieldBash"
    },
    "classOnly": "warrior",
    "id": "warrior_def_wall",
    "maxPoints": 1,
    "name": "방패 돌진",
    "specOnly": "방어"
  },
  "warrior_weapon_breaker": {
    "classOnly": "warrior",
    "doubleAttackPct": [
      0,
      0.25,
      0.5,
      0.75
    ],
    "id": "warrior_weapon_breaker",
    "maxPoints": 3,
    "name": "더블 어택",
    "specOnly": "무기"
  },
  "warrior_weapon_judgment": {
    "active": {
      "charge": true,
      "chargeMult": 2.8,
      "cooldown": 6,
      "name": "최후의 심판",
      "type": "charge"
    },
    "classOnly": "warrior",
    "id": "warrior_weapon_judgment",
    "maxPoints": 1,
    "name": "최후의 심판",
    "specOnly": "무기"
  },
  "warrior_weapon_mastery": {
    "classOnly": "warrior",
    "id": "warrior_weapon_mastery",
    "maxPoints": 5,
    "name": "무기 숙련",
    "reflectPct": [
      0,
      0.1,
      0.2,
      0.3,
      0.4,
      0.5
    ],
    "specOnly": "무기"
  },
  "warrior_weapon_rage": {
    "classOnly": "warrior",
    "id": "warrior_weapon_rage",
    "maxPoints": 3,
    "name": "전투의 대가",
    "specOnly": "무기"
  },
  "warrior_weapon_slash": {
    "active": {
      "cooldown": 5,
      "multiplier": 1.8,
      "name": "파쇄 일격",
      "stun": 1,
      "type": "damage"
    },
    "classOnly": "warrior",
    "id": "warrior_weapon_slash",
    "maxPoints": 1,
    "name": "파쇄 일격",
    "specOnly": "무기"
  }
});
