-- Server-authoritative quest progression and healing well.

create table if not exists public.game_quest_catalog_v3 (
  quest_id text primary key check (char_length(quest_id) between 1 and 80),
  sequence_number integer not null unique check (sequence_number between 1 and 100),
  event_kind text not null check (event_kind in ('action', 'monster', 'healing', 'questGift')),
  event_target text not null check (char_length(event_target) between 1 and 80),
  target_count integer not null check (target_count between 1 and 10000),
  reward_exp integer not null default 0 check (reward_exp >= 0),
  reward_gold integer not null default 0 check (reward_gold >= 0),
  reward_building integer not null default 0 check (reward_building >= 0),
  reward_item_id text references public.game_item_catalog_v3(item_id),
  accept_gold integer not null default 0 check (accept_gold >= 0),
  accept_building integer not null default 0 check (accept_building >= 0),
  accept_item_id text references public.game_item_catalog_v3(item_id)
);
-- BEGIN GENERATED QUEST CATALOG V3
-- Generated by tools/generate-quest-catalog-v3.mjs. Do not edit.
-- quests: 17

insert into public.game_quest_catalog_v3
  (quest_id, sequence_number, event_kind, event_target, target_count,
   reward_exp, reward_gold, reward_building, reward_item_id,
   accept_gold, accept_building, accept_item_id)
values
('tut_equip',1,'action','equip',1,5,35,0,null,0,0,'whiteCloak'),
('tut_healing_well',2,'healing','well',1,3,20,0,null,0,0,null),
('mushroom_hunt',3,'monster','forest_mushroom',4,5,40,3,null,0,0,null),
('tut_shop',4,'action','buy',1,8,50,3,null,0,0,null),
('tut_skill',5,'action','learnSkill',1,8,45,3,null,0,0,null),
('slime_hunt',6,'monster','forest_slime',3,8,48,3,null,0,0,null),
('tut_costume',7,'questGift','cs_questSproutRibbon',1,10,35,3,null,0,0,null),
('tut_accessory',8,'action','buyAccessory',1,12,45,3,null,0,5,null),
('elite_slime_hunt',9,'monster','forest_elite_slime',1,18,75,9,'honorCrown',0,0,null),
('tut_enhance',10,'action','enhance',1,15,100,3,null,0,0,null),
('stomp_hunt',11,'monster','desert_stomp',4,12,58,6,null,0,0,null),
('snake_hunt',12,'monster','desert_snake',4,16,68,6,null,0,0,null),
('tut_pet',13,'action','pet',1,20,60,6,null,0,0,null),
('elite_snake_hunt',14,'monster','desert_elite_snake',1,34,110,15,'starCape',0,0,null),
('swamp_spider_hunt',15,'monster','swamp_tarantula',4,22,85,9,null,0,0,null),
('swamp_zombie_hunt',16,'monster','swamp_zombie',4,28,95,9,null,0,0,null),
('swamp_king_hunt',17,'monster','swamp_elite_zombie',1,45,140,15,null,0,0,null)
on conflict (quest_id) do update set
  sequence_number = excluded.sequence_number, event_kind = excluded.event_kind,
  event_target = excluded.event_target, target_count = excluded.target_count,
  reward_exp = excluded.reward_exp, reward_gold = excluded.reward_gold,
  reward_building = excluded.reward_building, reward_item_id = excluded.reward_item_id,
  accept_gold = excluded.accept_gold, accept_building = excluded.accept_building,
  accept_item_id = excluded.accept_item_id;
-- END GENERATED QUEST CATALOG V3

create table if not exists public.player_healing_sessions_v3 (
  user_id uuid primary key references public.player_core_v3(user_id) on delete cascade,
  question_token uuid not null unique,
  safe_question jsonb not null check (jsonb_typeof(safe_question) = 'object'),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create table if not exists public.player_healing_question_secrets_v3 (
  user_id uuid primary key references public.player_healing_sessions_v3(user_id) on delete cascade,
  question_token uuid not null unique,
  answer_key text not null check (char_length(answer_key) between 1 and 512)
);
alter table public.game_quest_catalog_v3 enable row level security;
alter table public.game_quest_catalog_v3 force row level security;
alter table public.player_healing_sessions_v3 enable row level security;
alter table public.player_healing_sessions_v3 force row level security;
alter table public.player_healing_question_secrets_v3 enable row level security;
alter table public.player_healing_question_secrets_v3 force row level security;
revoke all on table public.game_quest_catalog_v3 from public, anon, authenticated;
revoke all on table public.player_healing_sessions_v3 from public, anon, authenticated;
revoke all on table public.player_healing_question_secrets_v3 from public, anon, authenticated;
create or replace function public.private_progress_student_quest_v3(
  p_user_id uuid,
  p_event_kind text,
  p_event_target text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer := 0;
begin
  update public.player_quests_v3 as q
  set progress = least(c.target_count, q.progress + 1),
      status = case when q.progress + 1 >= c.target_count then 'ready' else 'active' end,
      completed_at = case when q.progress + 1 >= c.target_count then coalesce(q.completed_at, now()) else q.completed_at end,
      updated_at = now()
  from public.game_quest_catalog_v3 as c
  where q.user_id = p_user_id
    and q.quest_id = c.quest_id
    and q.status = 'active'
    and c.event_kind = p_event_kind
    and c.event_target = p_event_target;
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;
create or replace function public.accept_student_quest_v3(
  p_quest_id text,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
  v_core public.player_core_v3%rowtype;
  v_quest public.game_quest_catalog_v3%rowtype;
begin
  if v_user_id is null then return jsonb_build_object('ok',false,'code','UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok',false,'code','FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    return jsonb_build_object('ok',false,'code','INVALID_REQUEST');
  end if;
  v_request_id := p_request_id::uuid;
  v_receipt := public.private_read_receipt_v3(v_request_id, 'accept_student_quest_v3');
  if v_receipt is not null then return v_receipt; end if;
  select * into v_core from public.player_core_v3 where user_id = v_user_id for update;
  if v_core.user_id is null then
    return public.private_store_receipt_v3(v_request_id,'accept_student_quest_v3',
      jsonb_build_object('ok',false,'code','CHARACTER_NOT_FOUND'));
  end if;
  if v_core.revision <> p_expected_revision then
    return public.private_store_receipt_v3(v_request_id,'accept_student_quest_v3',
      jsonb_build_object('ok',false,'code','REVISION_CONFLICT',
        'snapshot',public.private_build_student_snapshot_v3(v_user_id)));
  end if;
  select * into v_quest from public.game_quest_catalog_v3 where quest_id = p_quest_id;
  if v_quest.quest_id is null then
    return public.private_store_receipt_v3(v_request_id,'accept_student_quest_v3',
      jsonb_build_object('ok',false,'code','INVALID_QUEST'));
  end if;
  if exists (select 1 from public.player_quests_v3 where user_id=v_user_id and quest_id=p_quest_id)
    or (v_quest.sequence_number > 1 and not exists (
      select 1 from public.player_quests_v3 q
      join public.game_quest_catalog_v3 c on c.quest_id=q.quest_id
      where q.user_id=v_user_id
        and c.sequence_number = v_quest.sequence_number - 1
        and q.status = 'claimed'
    )) then
    return public.private_store_receipt_v3(v_request_id,'accept_student_quest_v3',
      jsonb_build_object('ok',false,'code','QUEST_LOCKED'));
  end if;
  insert into public.player_quests_v3(user_id,quest_id,status,progress,accepted_at)
  values(v_user_id,p_quest_id,'active',0,now());
  update public.player_core_v3 set
    gold=gold+v_quest.accept_gold,
    building=building+v_quest.accept_building,
    current_hp=case when p_quest_id='tut_healing_well' then 1 else current_hp end,
    revision=revision+1, updated_at=now()
  where user_id=v_user_id;
  if v_quest.accept_item_id is not null then
    insert into public.player_inventory_v3(
      user_id,item_definition_id,inventory_kind,enhancement_tier,equipped_slot,grant_source
    )
    select v_user_id,i.item_id,i.inventory_kind,0,null,'quest_accept'
    from public.game_item_catalog_v3 i where i.item_id=v_quest.accept_item_id
    on conflict do nothing;
  end if;
  if p_quest_id='tut_skill' and exists (
    select 1 from public.player_skills_v3 where user_id=v_user_id and rank>0
  ) then
    perform public.private_progress_student_quest_v3(v_user_id,'action','learnSkill');
  end if;
  v_response := jsonb_build_object('ok',true,'code','OK',
    'snapshot',public.private_build_student_snapshot_v3(v_user_id));
  return public.private_store_receipt_v3(v_request_id,'accept_student_quest_v3',v_response);
end;
$$;
create or replace function public.claim_student_quest_v3(
  p_quest_id text,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
  v_core public.player_core_v3%rowtype;
  v_quest public.game_quest_catalog_v3%rowtype;
  v_status text;
  v_new_exp integer;
  v_new_level integer;
begin
  if v_user_id is null then return jsonb_build_object('ok',false,'code','UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok',false,'code','FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    return jsonb_build_object('ok',false,'code','INVALID_REQUEST');
  end if;
  v_request_id := p_request_id::uuid;
  v_receipt := public.private_read_receipt_v3(v_request_id,'claim_student_quest_v3');
  if v_receipt is not null then return v_receipt; end if;
  select * into v_core from public.player_core_v3 where user_id=v_user_id for update;
  if v_core.user_id is null then return jsonb_build_object('ok',false,'code','CHARACTER_NOT_FOUND'); end if;
  if v_core.revision <> p_expected_revision then
    return public.private_store_receipt_v3(v_request_id,'claim_student_quest_v3',
      jsonb_build_object('ok',false,'code','REVISION_CONFLICT',
        'snapshot',public.private_build_student_snapshot_v3(v_user_id)));
  end if;
  select q.status into v_status
  from public.player_quests_v3 q
  where q.user_id=v_user_id and q.quest_id=p_quest_id for update;
  select * into v_quest
  from public.game_quest_catalog_v3
  where quest_id=p_quest_id;
  if v_status is null or v_status <> 'ready' then
    return public.private_store_receipt_v3(v_request_id,'claim_student_quest_v3',
      jsonb_build_object('ok',false,'code','QUEST_NOT_READY'));
  end if;
  v_new_exp := v_core.exp + v_quest.reward_exp;
  v_new_level := case when v_new_exp>=580 then 10 when v_new_exp>=470 then 9
    when v_new_exp>=370 then 8 when v_new_exp>=280 then 7 when v_new_exp>=200 then 6
    when v_new_exp>=130 then 5 when v_new_exp>=80 then 4 when v_new_exp>=40 then 3
    when v_new_exp>=10 then 2 else 1 end;
  v_new_level := greatest(v_core.level,least(10,v_new_level));
  update public.player_core_v3 set exp=v_new_exp,level=v_new_level,
    gold=gold+v_quest.reward_gold,building=building+v_quest.reward_building,
    max_hp=max_hp+(v_new_level-level)*2,
    current_hp=case when v_new_level>level then max_hp+(v_new_level-level)*2 else current_hp end,
    revision=revision+1,updated_at=now()
  where user_id=v_user_id;
  if v_quest.reward_item_id is not null then
    insert into public.player_inventory_v3(
      user_id,item_definition_id,inventory_kind,enhancement_tier,equipped_slot,grant_source
    )
    select v_user_id,i.item_id,i.inventory_kind,0,null,'quest_reward'
    from public.game_item_catalog_v3 i where i.item_id=v_quest.reward_item_id
    on conflict do nothing;
  end if;
  update public.player_quests_v3 set status='claimed',updated_at=now()
  where user_id=v_user_id and quest_id=p_quest_id;
  v_response:=jsonb_build_object('ok',true,'code','OK',
    'snapshot',public.private_build_student_snapshot_v3(v_user_id));
  return public.private_store_receipt_v3(v_request_id,'claim_student_quest_v3',v_response);
end;
$$;
create or replace function public.receive_student_quest_gift_v3(
  p_quest_id text,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid:=auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_core public.player_core_v3%rowtype;
  v_target text;
  v_response jsonb;
begin
  if v_user_id is null then return jsonb_build_object('ok',false,'code','UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok',false,'code','FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    return jsonb_build_object('ok',false,'code','INVALID_REQUEST');
  end if;
  v_request_id:=p_request_id::uuid;
  v_receipt:=public.private_read_receipt_v3(v_request_id,'receive_student_quest_gift_v3');
  if v_receipt is not null then return v_receipt; end if;
  select * into v_core from public.player_core_v3 where user_id=v_user_id for update;
  if v_core.revision <> p_expected_revision then
    return public.private_store_receipt_v3(v_request_id,'receive_student_quest_gift_v3',
      jsonb_build_object('ok',false,'code','REVISION_CONFLICT',
        'snapshot',public.private_build_student_snapshot_v3(v_user_id)));
  end if;
  select c.event_target into v_target
  from public.player_quests_v3 q join public.game_quest_catalog_v3 c using(quest_id)
  where q.user_id=v_user_id and q.quest_id=p_quest_id and q.status='active'
    and c.event_kind='questGift';
  if v_target is null then return jsonb_build_object('ok',false,'code','QUEST_NOT_ACTIVE'); end if;
  insert into public.player_inventory_v3(
    user_id,item_definition_id,inventory_kind,enhancement_tier,equipped_slot,grant_source
  )
  select v_user_id,i.item_id,i.inventory_kind,0,null,'quest_gift'
  from public.game_item_catalog_v3 i where i.item_id=v_target
  on conflict do nothing;
  perform public.private_progress_student_quest_v3(v_user_id,'questGift',v_target);
  update public.player_core_v3 set revision=revision+1,updated_at=now() where user_id=v_user_id;
  v_response:=jsonb_build_object('ok',true,'code','OK',
    'snapshot',public.private_build_student_snapshot_v3(v_user_id));
  return public.private_store_receipt_v3(v_request_id,'receive_student_quest_gift_v3',v_response);
end;
$$;
create or replace function public.private_normalize_combat_answer_v3(
  p_value text
)
returns text
language sql
immutable
set search_path = ''
as $$
  select pg_catalog.lower(
    pg_catalog.regexp_replace(pg_catalog.btrim(coalesce(p_value,'')), '\s+', '', 'g')
  );
$$;
create or replace function public.private_read_service_receipt_v3(
  p_user_id uuid,
  p_request_id uuid,
  p_action_name text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_action text;
  v_response jsonb;
begin
  select action_name,response_json into v_action,v_response
  from public.game_action_receipts_v3
  where user_id=p_user_id and request_id=p_request_id;
  if v_action is not null and v_action<>p_action_name then
    raise exception using message='REQUEST_ID_REUSED';
  end if;
  return v_response;
end;
$$;
create or replace function public.private_store_service_receipt_v3(
  p_user_id uuid,
  p_request_id uuid,
  p_action_name text,
  p_response jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.game_action_receipts_v3(user_id,request_id,action_name,response_json)
  values(p_user_id,p_request_id,p_action_name,p_response)
  on conflict(user_id,request_id) do nothing;
  return public.private_read_service_receipt_v3(p_user_id,p_request_id,p_action_name);
end;
$$;
create or replace function public.private_start_student_healing_v3(
  p_user_id uuid,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_core public.player_core_v3%rowtype;
  v_question jsonb;
  v_token uuid:=gen_random_uuid();
  v_safe jsonb;
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
begin
  perform public.private_require_service_role_v3();
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    raise exception using message='INVALID_REQUEST';
  end if;
  v_request_id:=p_request_id::uuid;
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_user_id::text||':'||v_request_id::text,0)
  );
  v_receipt:=public.private_read_service_receipt_v3(
    p_user_id,v_request_id,'private_start_student_healing_v3'
  );
  if v_receipt is not null then return v_receipt; end if;
  select * into v_core from public.player_core_v3 where user_id=p_user_id for update;
  if v_core.user_id is null then raise exception using message='PLAYER_NOT_FOUND'; end if;
  if v_core.revision <> p_expected_revision then raise exception using message='PLAYER_REVISION_CONFLICT'; end if;
  v_question:=public.private_pick_combat_question_v3('forest');
  v_safe:=(v_question-'answerKey')||jsonb_build_object('questionToken',v_token);
  insert into public.player_healing_sessions_v3(user_id,question_token,safe_question,expires_at)
  values(p_user_id,v_token,v_safe,now()+interval '5 minutes')
  on conflict(user_id) do update set question_token=v_token,safe_question=v_safe,
    expires_at=excluded.expires_at,created_at=now();
  insert into public.player_healing_question_secrets_v3(user_id,question_token,answer_key)
  values(p_user_id,v_token,v_question->>'answerKey')
  on conflict(user_id) do update set question_token=v_token,answer_key=excluded.answer_key;
  v_response:=jsonb_build_object('ok',true,'question',v_safe);
  return public.private_store_service_receipt_v3(
    p_user_id,v_request_id,'private_start_student_healing_v3',v_response
  );
end;
$$;
create or replace function public.private_submit_student_healing_v3(
  p_user_id uuid,
  p_question_token uuid,
  p_answer text,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_session public.player_healing_sessions_v3%rowtype;
  v_answer text;
  v_correct boolean;
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
begin
  perform public.private_require_service_role_v3();
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    raise exception using message='INVALID_REQUEST';
  end if;
  v_request_id:=p_request_id::uuid;
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_user_id::text||':'||v_request_id::text,0)
  );
  v_receipt:=public.private_read_service_receipt_v3(
    p_user_id,v_request_id,'private_submit_student_healing_v3'
  );
  if v_receipt is not null then return v_receipt; end if;
  select * into v_session from public.player_healing_sessions_v3
  where user_id=p_user_id for update;
  select answer_key into v_answer from public.player_healing_question_secrets_v3
  where user_id=p_user_id and question_token=p_question_token;
  if v_session.user_id is null or v_session.question_token<>p_question_token
    or v_session.expires_at<=now() or v_answer is null then
    raise exception using message='HEALING_NOT_ACTIVE';
  end if;
  v_correct:=public.private_normalize_combat_answer_v3(p_answer)
    =public.private_normalize_combat_answer_v3(v_answer);
  delete from public.player_healing_sessions_v3 where user_id=p_user_id;
  if v_correct then
    update public.player_core_v3 set current_hp=max_hp,revision=revision+1,updated_at=now()
    where user_id=p_user_id and revision=p_expected_revision;
    if not found then raise exception using message='PLAYER_REVISION_CONFLICT'; end if;
    perform public.private_progress_student_quest_v3(p_user_id,'healing','well');
  end if;
  v_response:=jsonb_build_object('ok',true,'correct',v_correct,
    'player',public.private_build_student_snapshot_v3(p_user_id));
  return public.private_store_service_receipt_v3(
    p_user_id,v_request_id,'private_submit_student_healing_v3',v_response
  );
end;
$$;
revoke all on function public.private_progress_student_quest_v3(uuid,text,text) from public,anon,authenticated;
revoke all on function public.private_normalize_combat_answer_v3(text) from public,anon,authenticated;
revoke all on function public.private_read_service_receipt_v3(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.private_store_service_receipt_v3(uuid,uuid,text,jsonb) from public,anon,authenticated;
revoke all on function public.private_start_student_healing_v3(uuid,bigint,text) from public,anon,authenticated;
revoke all on function public.private_submit_student_healing_v3(uuid,uuid,text,bigint,text) from public,anon,authenticated;
grant execute on function public.private_start_student_healing_v3(uuid,bigint,text) to service_role;
grant execute on function public.private_submit_student_healing_v3(uuid,uuid,text,bigint,text) to service_role;
revoke all on function public.accept_student_quest_v3(text,bigint,text) from public,anon;
revoke all on function public.claim_student_quest_v3(text,bigint,text) from public,anon;
revoke all on function public.receive_student_quest_gift_v3(text,bigint,text) from public,anon;
grant execute on function public.accept_student_quest_v3(text,bigint,text) to authenticated;
grant execute on function public.claim_student_quest_v3(text,bigint,text) to authenticated;
grant execute on function public.receive_student_quest_gift_v3(text,bigint,text) to authenticated;
