-- Phase 2: server-authoritative economy, equipment, and skills.

create table if not exists public.game_item_catalog_v3 (
  item_id text primary key check (char_length(item_id) between 1 and 80),
  inventory_kind text not null check (inventory_kind in ('gear', 'costume')),
  currency_kind text not null check (currency_kind in ('gold', 'building', 'none')),
  price integer not null check (price >= 0),
  slot text not null check (slot in ('weapon', 'head', 'armor', 'accessory')),
  class_name text check (class_name is null or class_name in ('warrior', 'mage', 'priest')),
  level_required integer not null check (level_required between 1 and 10),
  quest_only boolean not null default false
);

create table if not exists public.game_skill_catalog_v3 (
  skill_id text primary key check (char_length(skill_id) between 1 and 80),
  class_name text not null check (class_name in ('warrior', 'mage', 'priest')),
  spec_name text,
  unlock_level integer not null check (unlock_level between 1 and 10),
  max_rank integer not null check (max_rank between 1 and 20),
  point_cost integer not null check (point_cost between 1 and 20),
  prerequisites jsonb not null check (jsonb_typeof(prerequisites) = 'object')
);

create table if not exists public.game_specialization_catalog_v3 (
  class_name text not null check (class_name in ('warrior', 'mage', 'priest')),
  spec_name text not null,
  primary key (class_name, spec_name)
);

alter table public.game_item_catalog_v3 enable row level security;
alter table public.game_item_catalog_v3 force row level security;
alter table public.game_skill_catalog_v3 enable row level security;
alter table public.game_skill_catalog_v3 force row level security;
alter table public.game_specialization_catalog_v3 enable row level security;
alter table public.game_specialization_catalog_v3 force row level security;

revoke all on table public.game_item_catalog_v3 from public, anon, authenticated;
revoke all on table public.game_skill_catalog_v3 from public, anon, authenticated;
revoke all on table public.game_specialization_catalog_v3 from public, anon, authenticated;

alter table public.player_inventory_v3
  add column inventory_kind text not null default 'gear'
  check (inventory_kind in ('gear', 'costume'));
alter table public.player_inventory_v3
  drop constraint if exists player_inventory_v3_user_id_equipped_slot_key;
create unique index if not exists player_inventory_v3_kind_slot_uidx
  on public.player_inventory_v3(user_id, inventory_kind, equipped_slot)
  where equipped_slot is not null;
create unique index if not exists player_inventory_v3_kind_item_uidx
  on public.player_inventory_v3(user_id, inventory_kind, item_definition_id);

-- BEGIN GENERATED AUTHORITY CATALOG V3
-- Generated by tools/generate-authority-catalog-v3.mjs. Do not edit.
-- base-items: 40
-- costumes: 11
-- total-items: 51
-- skills: 42

insert into public.game_item_catalog_v3
  (item_id, inventory_kind, currency_kind, price, slot, class_name, level_required, quest_only)
values
('blueSword','gear','gold',70,'weapon','warrior',3,false),
('blueWizardHat','gear','gold',55,'head','mage',3,false),
('bronzeGreatsword','gear','gold',30,'weapon','warrior',1,false),
('cloverBadge','gear','building',5,'accessory',null,3,false),
('crimsonArmor','gear','gold',320,'armor','warrior',9,false),
('crimsonHelm','gear','gold',260,'head','warrior',9,false),
('crystalStaff','gear','gold',30,'weapon','mage',1,false),
('dawnTome','gear','gold',320,'weapon','priest',9,false),
('featherWing','gear','building',5,'accessory',null,3,false),
('forestCloak','gear','gold',30,'armor',null,1,false),
('goldCirclet','gear','gold',130,'head','priest',6,false),
('goldVestment','gear','gold',160,'armor','priest',6,false),
('guardAura','gear','building',5,'accessory',null,3,false),
('holyBook','gear','gold',30,'weapon','priest',1,false),
('honorCrown','gear','none',0,'head',null,1,true),
('ironSword','gear','gold',160,'weapon','warrior',6,false),
('ironwoodStaff','gear','gold',160,'weapon','mage',6,false),
('leatherArmor','gear','gold',70,'armor','warrior',3,false),
('leatherHelm','gear','gold',55,'head','warrior',3,false),
('mithrilStaff','gear','gold',320,'weapon','mage',9,false),
('mithrilSword','gear','gold',320,'weapon','warrior',9,false),
('navyRobe','gear','gold',160,'armor','mage',6,false),
('navyWizardHat','gear','gold',130,'head','mage',6,false),
('noviceHat','gear','gold',20,'head',null,1,false),
('oakStaff','gear','gold',70,'weapon','mage',3,false),
('prayerBook','gear','gold',70,'weapon','priest',3,false),
('roseHood','gear','gold',260,'head','priest',9,false),
('roseVestment','gear','gold',320,'armor','priest',9,false),
('silverBook','gear','gold',160,'weapon','priest',6,false),
('sixthWing','gear','building',5,'accessory',null,3,false),
('skyRobe','gear','gold',70,'armor','mage',3,false),
('starCape','gear','none',0,'armor',null,1,true),
('starPendant','gear','building',5,'accessory',null,3,false),
('steelArmor','gear','gold',160,'armor','warrior',6,false),
('steelHelm','gear','gold',130,'head','warrior',6,false),
('violetRobe','gear','gold',320,'armor','mage',9,false),
('violetWizardHat','gear','gold',260,'head','mage',9,false),
('whiteCloak','gear','none',0,'armor',null,1,true),
('whiteHood','gear','gold',55,'head','priest',3,false),
('whiteVestment','gear','gold',70,'armor','priest',3,false),
('cs_angelWing','costume','gold',380,'accessory',null,1,false),
('cs_bunnyBand','costume','gold',120,'head',null,1,false),
('cs_flowerCrown','costume','gold',260,'head',null,1,false),
('cs_peachDress','costume','gold',420,'armor',null,1,false),
('cs_questSproutRibbon','costume','none',0,'accessory',null,1,true),
('cs_rainbowAura','costume','gold',500,'accessory',null,1,false),
('cs_ribbon','costume','gold',100,'accessory',null,1,false),
('cs_sailorCape','costume','gold',150,'armor',null,1,false),
('cs_starCrown','costume','gold',480,'head',null,1,false),
('cs_starryRobe','costume','gold',320,'armor',null,1,false),
('cs_strangeWing','costume','gold',440,'accessory',null,1,false)
on conflict (item_id) do update set
  inventory_kind = excluded.inventory_kind, currency_kind = excluded.currency_kind,
  price = excluded.price, slot = excluded.slot, class_name = excluded.class_name,
  level_required = excluded.level_required, quest_only = excluded.quest_only;

insert into public.game_skill_catalog_v3
  (skill_id, class_name, spec_name, unlock_level, max_rank, point_cost, prerequisites)
values
('mage_basic_barrier','mage',null,1,1,1,'{"all":["mage_basic_bolt"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_basic_bolt','mage',null,1,1,1,'{"all":["mage_basic_element"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_basic_element','mage',null,1,5,1,'{"all":["mage_basic_mana"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_basic_mana','mage',null,1,5,1,'{"all":[],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fire_burst_v24','mage','화염',7,1,1,'{"all":["mage_fire_ember_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fire_ember_v24','mage','화염',7,5,1,'{"all":["mage_fireball_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fire_focus_v24','mage','화염',5,3,1,'{"all":["mage_basic_barrier"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fire_meteor_v24','mage','화염',9,1,1,'{"all":["mage_fire_burst_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fireball_v24','mage','화염',5,1,1,'{"all":["mage_fire_focus_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_armor_v24','mage','냉기',7,1,1,'{"all":["mage_frost_lance_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_focus_v24','mage','냉기',5,3,1,'{"all":["mage_basic_barrier"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_lance_v24','mage','냉기',5,1,1,'{"all":["mage_frost_focus_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_mind_v24','mage','냉기',7,5,1,'{"all":["mage_frost_armor_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_storm_v24','mage','냉기',9,1,1,'{"all":["mage_frost_mind_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_basic_faith','priest',null,1,3,1,'{"all":[],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_basic_life','priest',null,1,5,1,'{"all":["priest_basic_faith"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_basic_prayer','priest',null,1,3,1,'{"all":["priest_basic_smite"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_basic_smite','priest',null,1,1,1,'{"all":["priest_basic_life"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_absorb_v24','priest','신성',5,1,1,'{"all":["priest_holy_focus_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_barrier_v24','priest','신성',7,1,1,'{"all":["priest_holy_absorb_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_focus_v24','priest','신성',5,5,1,'{"all":["priest_basic_prayer"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_grace_v24','priest','신성',7,3,1,'{"all":["priest_holy_barrier_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_judgment_v24','priest','신성',9,1,1,'{"all":["priest_holy_grace_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_focus_v24','priest','암흑',5,5,1,'{"all":["priest_basic_prayer"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_judgment_v24','priest','암흑',9,1,1,'{"all":["priest_shadow_void_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_mark_v24','priest','암흑',7,1,1,'{"all":["priest_shadow_seed_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_seed_v24','priest','암흑',5,1,1,'{"all":["priest_shadow_focus_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_void_v24','priest','암흑',7,5,1,'{"all":["priest_shadow_mark_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_basic_blade','warrior',null,1,3,1,'{"all":["warrior_basic_body"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_basic_body','warrior',null,1,3,1,'{"all":[],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_basic_guard','warrior',null,1,3,1,'{"all":["warrior_basic_blade"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_basic_strike','warrior',null,1,1,1,'{"all":["warrior_basic_guard"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_armor','warrior','방어',5,5,1,'{"all":["warrior_def_stance"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_bastion','warrior','방어',9,1,1,'{"all":["warrior_def_wall"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_resist','warrior','방어',7,5,1,'{"all":["warrior_def_armor"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_stance','warrior','방어',5,1,1,'{"all":["warrior_basic_strike"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_wall','warrior','방어',7,1,1,'{"all":["warrior_def_resist"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_breaker','warrior','무기',7,3,1,'{"all":["warrior_weapon_rage"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_judgment','warrior','무기',9,1,1,'{"all":["warrior_weapon_breaker"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_mastery','warrior','무기',5,5,1,'{"all":["warrior_basic_strike"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_rage','warrior','무기',7,3,1,'{"all":["warrior_weapon_slash"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_slash','warrior','무기',5,1,1,'{"all":["warrior_weapon_mastery"],"ranks":{},"any":[],"total":null}'::jsonb)
on conflict (skill_id) do update set
  class_name = excluded.class_name, spec_name = excluded.spec_name,
  unlock_level = excluded.unlock_level, max_rank = excluded.max_rank,
  point_cost = excluded.point_cost, prerequisites = excluded.prerequisites;

insert into public.game_specialization_catalog_v3(class_name, spec_name) values
('warrior','방어'),
('warrior','무기'),
('mage','냉기'),
('mage','화염'),
('priest','신성'),
('priest','암흑')
on conflict (class_name, spec_name) do nothing;
-- END GENERATED AUTHORITY CATALOG V3


alter function public.private_build_student_snapshot_v3(uuid)
  rename to private_build_student_snapshot_v3_phase1;

create or replace function public.private_build_student_snapshot_v3(
  p_user_id uuid
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when base.snapshot is null then null
    else jsonb_set(
      base.snapshot,
      '{inventory}',
      coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', i.id,
          'item_definition_id', i.item_definition_id,
          'inventory_kind', i.inventory_kind,
          'enhancement_tier', i.enhancement_tier,
          'equipped_slot', i.equipped_slot
        ) order by i.inventory_kind, i.item_definition_id, i.id)
        from public.player_inventory_v3 as i
        where i.user_id = p_user_id
      ), '[]'::jsonb)
    )
  end
  from (
    select public.private_build_student_snapshot_v3_phase1(p_user_id) as snapshot
  ) as base;
$$;

revoke all on function public.private_build_student_snapshot_v3_phase1(uuid)
  from public, anon, authenticated;
revoke all on function public.private_build_student_snapshot_v3(uuid)
  from public, anon, authenticated;

create or replace function public.purchase_student_item_v3(
  p_item_id text,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
  v_current_revision bigint;
  v_class_name text;
  v_level integer;
  v_gold integer;
  v_building integer;
  v_kind text;
  v_currency_kind text;
  v_price integer;
  v_slot text;
  v_item_class text;
  v_level_required integer;
  v_quest_only boolean;
begin
  if v_user_id is null then return jsonb_build_object('ok', false, 'code', 'UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok', false, 'code', 'FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    perform public.private_log_security_event_v3('invalid_request_id', '{}'::jsonb);
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;
  v_request_id := p_request_id::uuid;
  v_receipt := public.private_read_receipt_v3(v_request_id, 'purchase_student_item_v3');
  if v_receipt is not null then return v_receipt; end if;

  select c.revision, c.class_name, c.level, c.gold, c.building
  into v_current_revision, v_class_name, v_level, v_gold, v_building
  from public.player_core_v3 as c where c.user_id = v_user_id for update;
  if v_current_revision is null then
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'CHARACTER_NOT_FOUND'));
  end if;
  if p_expected_revision is distinct from v_current_revision then
    v_response := jsonb_build_object('ok', false, 'code', 'REVISION_CONFLICT',
      'snapshot', public.private_build_student_snapshot_v3(v_user_id));
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3', v_response);
  end if;
  if p_item_id is null or char_length(p_item_id) not between 1 and 80 then
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'INVALID_ITEM'));
  end if;

  select i.inventory_kind, i.currency_kind, i.price, i.slot, i.class_name,
    i.level_required, i.quest_only
  into v_kind, v_currency_kind, v_price, v_slot, v_item_class,
    v_level_required, v_quest_only
  from public.game_item_catalog_v3 as i where i.item_id = p_item_id;
  if v_kind is null then
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'INVALID_ITEM'));
  end if;
  if v_quest_only or v_currency_kind = 'none' then
    perform public.private_log_security_event_v3('item_not_purchasable', '{}'::jsonb);
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'ITEM_NOT_PURCHASABLE'));
  end if;
  if v_item_class is not null and v_item_class is distinct from v_class_name then
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'CLASS_REQUIRED'));
  end if;
  if v_level < v_level_required then
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'LEVEL_REQUIRED'));
  end if;
  if exists (
    select 1 from public.player_inventory_v3
    where user_id = v_user_id and inventory_kind = v_kind
      and item_definition_id = p_item_id
  ) then
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'ALREADY_OWNED'));
  end if;
  if (v_currency_kind = 'gold' and v_gold < v_price)
    or (v_currency_kind = 'building' and v_building < v_price) then
    return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'INSUFFICIENT_FUNDS'));
  end if;

  update public.player_core_v3
  set gold = case when v_currency_kind = 'gold' then gold - v_price else gold end,
      building = case when v_currency_kind = 'building' then building - v_price else building end,
      revision = revision + 1,
      updated_at = now()
  where user_id = v_user_id;
  insert into public.player_inventory_v3(
    user_id, item_definition_id, inventory_kind, enhancement_tier, equipped_slot, grant_source
  ) values (v_user_id, p_item_id, v_kind, 0, null, 'purchase');

  v_response := jsonb_build_object('ok', true, 'code', 'OK',
    'snapshot', public.private_build_student_snapshot_v3(v_user_id));
  return public.private_store_receipt_v3(v_request_id, 'purchase_student_item_v3', v_response);
end;
$$;

create or replace function public.equip_student_item_v3(
  p_inventory_id uuid,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
  v_current_revision bigint;
  v_class_name text;
  v_level integer;
  v_kind text;
  v_slot text;
  v_item_class text;
  v_level_required integer;
begin
  if v_user_id is null then return jsonb_build_object('ok', false, 'code', 'UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok', false, 'code', 'FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    perform public.private_log_security_event_v3('invalid_request_id', '{}'::jsonb);
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;
  v_request_id := p_request_id::uuid;
  v_receipt := public.private_read_receipt_v3(v_request_id, 'equip_student_item_v3');
  if v_receipt is not null then return v_receipt; end if;

  select c.revision, c.class_name, c.level
  into v_current_revision, v_class_name, v_level
  from public.player_core_v3 as c where c.user_id = v_user_id for update;
  if v_current_revision is null then
    return public.private_store_receipt_v3(v_request_id, 'equip_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'CHARACTER_NOT_FOUND'));
  end if;
  if p_expected_revision is distinct from v_current_revision then
    v_response := jsonb_build_object('ok', false, 'code', 'REVISION_CONFLICT',
      'snapshot', public.private_build_student_snapshot_v3(v_user_id));
    return public.private_store_receipt_v3(v_request_id, 'equip_student_item_v3', v_response);
  end if;

  select i.inventory_kind, c.slot, c.class_name, c.level_required
  into v_kind, v_slot, v_item_class, v_level_required
  from public.player_inventory_v3 as i
  join public.game_item_catalog_v3 as c on c.item_id = i.item_definition_id
  where i.user_id = v_user_id and i.id = p_inventory_id
  for update of i;
  if v_kind is null then
    perform public.private_log_security_event_v3('equip_unowned_item', '{}'::jsonb);
    return public.private_store_receipt_v3(v_request_id, 'equip_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'ITEM_NOT_OWNED'));
  end if;
  if v_item_class is not null and v_item_class is distinct from v_class_name then
    return public.private_store_receipt_v3(v_request_id, 'equip_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'CLASS_REQUIRED'));
  end if;
  if v_level < v_level_required then
    return public.private_store_receipt_v3(v_request_id, 'equip_student_item_v3',
      jsonb_build_object('ok', false, 'code', 'LEVEL_REQUIRED'));
  end if;

  update public.player_inventory_v3
  set equipped_slot = null, updated_at = now()
  where user_id = v_user_id and inventory_kind = v_kind and equipped_slot = v_slot;
  update public.player_inventory_v3
  set equipped_slot = v_slot, updated_at = now()
  where user_id = v_user_id and id = p_inventory_id;
  update public.player_core_v3
  set revision = revision + 1, updated_at = now() where user_id = v_user_id;

  v_response := jsonb_build_object('ok', true, 'code', 'OK',
    'snapshot', public.private_build_student_snapshot_v3(v_user_id));
  return public.private_store_receipt_v3(v_request_id, 'equip_student_item_v3', v_response);
end;
$$;

create or replace function public.unequip_student_slot_v3(
  p_inventory_kind text,
  p_slot text,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
  v_current_revision bigint;
  v_changed integer;
begin
  if v_user_id is null then return jsonb_build_object('ok', false, 'code', 'UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok', false, 'code', 'FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    perform public.private_log_security_event_v3('invalid_request_id', '{}'::jsonb);
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;
  v_request_id := p_request_id::uuid;
  v_receipt := public.private_read_receipt_v3(v_request_id, 'unequip_student_slot_v3');
  if v_receipt is not null then return v_receipt; end if;

  select c.revision into v_current_revision
  from public.player_core_v3 as c where c.user_id = v_user_id for update;
  if v_current_revision is null then
    return public.private_store_receipt_v3(v_request_id, 'unequip_student_slot_v3',
      jsonb_build_object('ok', false, 'code', 'CHARACTER_NOT_FOUND'));
  end if;
  if p_expected_revision is distinct from v_current_revision then
    v_response := jsonb_build_object('ok', false, 'code', 'REVISION_CONFLICT',
      'snapshot', public.private_build_student_snapshot_v3(v_user_id));
    return public.private_store_receipt_v3(v_request_id, 'unequip_student_slot_v3', v_response);
  end if;
  if p_inventory_kind is null or p_inventory_kind not in ('gear', 'costume')
    or p_slot is null or p_slot not in ('weapon', 'head', 'armor', 'accessory') then
    return public.private_store_receipt_v3(v_request_id, 'unequip_student_slot_v3',
      jsonb_build_object('ok', false, 'code', 'INVALID_SLOT'));
  end if;

  update public.player_inventory_v3
  set equipped_slot = null, updated_at = now()
  where user_id = v_user_id
    and inventory_kind = p_inventory_kind
    and equipped_slot = p_slot;
  get diagnostics v_changed = row_count;
  if v_changed = 0 then
    return public.private_store_receipt_v3(v_request_id, 'unequip_student_slot_v3',
      jsonb_build_object('ok', false, 'code', 'SLOT_EMPTY'));
  end if;
  update public.player_core_v3
  set revision = revision + 1, updated_at = now() where user_id = v_user_id;
  v_response := jsonb_build_object('ok', true, 'code', 'OK',
    'snapshot', public.private_build_student_snapshot_v3(v_user_id));
  return public.private_store_receipt_v3(v_request_id, 'unequip_student_slot_v3', v_response);
end;
$$;

revoke all on function public.purchase_student_item_v3(text, bigint, text) from public, anon;
revoke all on function public.equip_student_item_v3(uuid, bigint, text) from public, anon;
revoke all on function public.unequip_student_slot_v3(text, text, bigint, text) from public, anon;
grant execute on function public.purchase_student_item_v3(text, bigint, text) to authenticated;
grant execute on function public.equip_student_item_v3(uuid, bigint, text) to authenticated;
grant execute on function public.unequip_student_slot_v3(text, text, bigint, text) to authenticated;

create or replace function public.enhance_student_weapon_v3(
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
  v_current_revision bigint;
  v_building integer;
  v_inventory_id uuid;
  v_current_tier integer;
  v_new_tier integer;
  v_chance numeric;
  v_success boolean;
begin
  if v_user_id is null then return jsonb_build_object('ok', false, 'code', 'UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok', false, 'code', 'FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    perform public.private_log_security_event_v3('invalid_request_id', '{}'::jsonb);
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;
  v_request_id := p_request_id::uuid;
  v_receipt := public.private_read_receipt_v3(v_request_id, 'enhance_student_weapon_v3');
  if v_receipt is not null then return v_receipt; end if;

  select c.revision, c.building into v_current_revision, v_building
  from public.player_core_v3 as c where c.user_id = v_user_id for update;
  if v_current_revision is null then
    return public.private_store_receipt_v3(v_request_id, 'enhance_student_weapon_v3',
      jsonb_build_object('ok', false, 'code', 'CHARACTER_NOT_FOUND'));
  end if;
  if p_expected_revision is distinct from v_current_revision then
    v_response := jsonb_build_object('ok', false, 'code', 'REVISION_CONFLICT',
      'snapshot', public.private_build_student_snapshot_v3(v_user_id));
    return public.private_store_receipt_v3(v_request_id, 'enhance_student_weapon_v3', v_response);
  end if;

  select i.id, i.enhancement_tier into v_inventory_id, v_current_tier
  from public.player_inventory_v3 as i
  where i.user_id = v_user_id and i.inventory_kind = 'gear'
    and i.equipped_slot = 'weapon'
  for update;
  if v_inventory_id is null then
    return public.private_store_receipt_v3(v_request_id, 'enhance_student_weapon_v3',
      jsonb_build_object('ok', false, 'code', 'WEAPON_NOT_EQUIPPED'));
  end if;
  if v_current_tier >= 4 then
    return public.private_store_receipt_v3(v_request_id, 'enhance_student_weapon_v3',
      jsonb_build_object('ok', false, 'code', 'MAX_TIER'));
  end if;
  if v_building < 3 then
    return public.private_store_receipt_v3(v_request_id, 'enhance_student_weapon_v3',
      jsonb_build_object('ok', false, 'code', 'INSUFFICIENT_FUNDS'));
  end if;

  v_chance := case v_current_tier
    when 0 then 0.80 when 1 then 0.60 when 2 then 0.40 when 3 then 0.20
    else 0
  end;
  v_success := pg_catalog.random() < v_chance;
  v_new_tier := case when v_success then v_current_tier + 1
    else greatest(0, v_current_tier - 1) end;
  update public.player_inventory_v3
  set enhancement_tier = v_new_tier, updated_at = now()
  where id = v_inventory_id and user_id = v_user_id;
  update public.player_core_v3
  set building = building - 3, revision = revision + 1, updated_at = now()
  where user_id = v_user_id;

  v_response := jsonb_build_object(
    'ok', true, 'code', 'OK',
    'snapshot', public.private_build_student_snapshot_v3(v_user_id),
    'outcome', jsonb_build_object(
      'success', v_success, 'old_tier', v_current_tier, 'new_tier', v_new_tier
    )
  );
  return public.private_store_receipt_v3(v_request_id, 'enhance_student_weapon_v3', v_response);
end;
$$;

create or replace function public.choose_student_specialization_v3(
  p_spec_name text,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
  v_current_revision bigint;
  v_class_name text;
  v_level integer;
  v_current_spec text;
begin
  if v_user_id is null then return jsonb_build_object('ok', false, 'code', 'UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok', false, 'code', 'FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    perform public.private_log_security_event_v3('invalid_request_id', '{}'::jsonb);
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;
  v_request_id := p_request_id::uuid;
  v_receipt := public.private_read_receipt_v3(v_request_id, 'choose_student_specialization_v3');
  if v_receipt is not null then return v_receipt; end if;

  select c.revision, c.class_name, c.level, c.spec
  into v_current_revision, v_class_name, v_level, v_current_spec
  from public.player_core_v3 as c where c.user_id = v_user_id for update;
  if v_current_revision is null then
    return public.private_store_receipt_v3(v_request_id, 'choose_student_specialization_v3',
      jsonb_build_object('ok', false, 'code', 'CHARACTER_NOT_FOUND'));
  end if;
  if p_expected_revision is distinct from v_current_revision then
    v_response := jsonb_build_object('ok', false, 'code', 'REVISION_CONFLICT',
      'snapshot', public.private_build_student_snapshot_v3(v_user_id));
    return public.private_store_receipt_v3(v_request_id, 'choose_student_specialization_v3', v_response);
  end if;
  if v_current_spec is not null then
    return public.private_store_receipt_v3(v_request_id, 'choose_student_specialization_v3',
      jsonb_build_object('ok', false, 'code', 'SPECIALIZATION_ALREADY_CHOSEN'));
  end if;
  if v_level < 5 then
    return public.private_store_receipt_v3(v_request_id, 'choose_student_specialization_v3',
      jsonb_build_object('ok', false, 'code', 'LEVEL_REQUIRED'));
  end if;
  if p_spec_name is null or not exists (
    select 1 from public.game_specialization_catalog_v3
    where class_name = v_class_name and spec_name = p_spec_name
  ) then
    perform public.private_log_security_event_v3('invalid_specialization', '{}'::jsonb);
    return public.private_store_receipt_v3(v_request_id, 'choose_student_specialization_v3',
      jsonb_build_object('ok', false, 'code', 'INVALID_SPECIALIZATION'));
  end if;
  update public.player_core_v3
  set spec = p_spec_name, revision = revision + 1, updated_at = now()
  where user_id = v_user_id;
  v_response := jsonb_build_object('ok', true, 'code', 'OK',
    'snapshot', public.private_build_student_snapshot_v3(v_user_id));
  return public.private_store_receipt_v3(v_request_id, 'choose_student_specialization_v3', v_response);
end;
$$;

create or replace function public.learn_student_skill_v3(
  p_skill_id text,
  p_expected_revision bigint,
  p_request_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id uuid;
  v_receipt jsonb;
  v_response jsonb;
  v_current_revision bigint;
  v_class_name text;
  v_spec text;
  v_level integer;
  v_skill_class text;
  v_skill_spec text;
  v_unlock_level integer;
  v_max_rank integer;
  v_point_cost integer;
  v_prerequisites jsonb;
  v_current_rank integer;
  v_spent_points integer;
  v_available_points integer;
begin
  if v_user_id is null then return jsonb_build_object('ok', false, 'code', 'UNAUTHORIZED'); end if;
  if public.private_is_teacher_v3() then return jsonb_build_object('ok', false, 'code', 'FORBIDDEN'); end if;
  if p_request_id is null or p_request_id !~* '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' then
    perform public.private_log_security_event_v3('invalid_request_id', '{}'::jsonb);
    return jsonb_build_object('ok', false, 'code', 'INVALID_REQUEST');
  end if;
  v_request_id := p_request_id::uuid;
  v_receipt := public.private_read_receipt_v3(v_request_id, 'learn_student_skill_v3');
  if v_receipt is not null then return v_receipt; end if;

  select c.revision, c.class_name, c.spec, c.level
  into v_current_revision, v_class_name, v_spec, v_level
  from public.player_core_v3 as c where c.user_id = v_user_id for update;
  if v_current_revision is null then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'CHARACTER_NOT_FOUND'));
  end if;
  if p_expected_revision is distinct from v_current_revision then
    v_response := jsonb_build_object('ok', false, 'code', 'REVISION_CONFLICT',
      'snapshot', public.private_build_student_snapshot_v3(v_user_id));
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3', v_response);
  end if;

  select s.class_name, s.spec_name, s.unlock_level, s.max_rank,
    s.point_cost, s.prerequisites
  into v_skill_class, v_skill_spec, v_unlock_level, v_max_rank,
    v_point_cost, v_prerequisites
  from public.game_skill_catalog_v3 as s where s.skill_id = p_skill_id;
  if v_skill_class is null then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'INVALID_SKILL'));
  end if;
  if v_skill_class is distinct from v_class_name then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'CLASS_REQUIRED'));
  end if;
  if v_skill_spec is not null and v_skill_spec is distinct from v_spec then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'SPECIALIZATION_REQUIRED'));
  end if;
  if v_level < v_unlock_level then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'LEVEL_REQUIRED'));
  end if;

  select coalesce(s.rank, 0) into v_current_rank
  from public.player_skills_v3 as s
  where s.user_id = v_user_id and s.skill_id = p_skill_id;
  v_current_rank := coalesce(v_current_rank, 0);
  if v_current_rank >= v_max_rank then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'MAX_RANK'));
  end if;
  select coalesce(sum(ps.rank * catalog.point_cost), 0)::integer
  into v_spent_points
  from public.player_skills_v3 as ps
  join public.game_skill_catalog_v3 as catalog on catalog.skill_id = ps.skill_id
  where ps.user_id = v_user_id;
  v_available_points := (v_level - 1) * 2 - v_spent_points;
  if v_available_points < v_point_cost then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'SKILL_POINTS_REQUIRED'));
  end if;

  if exists (
    select 1 from jsonb_array_elements_text(v_prerequisites -> 'all') as req(skill_id)
    where coalesce((
      select rank from public.player_skills_v3
      where user_id = v_user_id and skill_id = req.skill_id
    ), 0) < 1
  ) or exists (
    select 1 from jsonb_each_text(v_prerequisites -> 'ranks') as req(skill_id, required_rank)
    where coalesce((
      select rank from public.player_skills_v3
      where user_id = v_user_id and skill_id = req.skill_id
    ), 0) < req.required_rank::integer
  ) then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'PREREQUISITE_REQUIRED'));
  end if;
  if jsonb_array_length(v_prerequisites -> 'any') > 0 and not exists (
    select 1 from jsonb_array_elements_text(v_prerequisites -> 'any') as req(skill_id)
    join public.player_skills_v3 as owned
      on owned.user_id = v_user_id and owned.skill_id = req.skill_id and owned.rank > 0
  ) then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'PREREQUISITE_REQUIRED'));
  end if;
  if jsonb_typeof(v_prerequisites -> 'total') = 'object' and (
    select coalesce(sum(owned.rank), 0)
    from jsonb_array_elements_text(v_prerequisites -> 'total' -> 'ids') as req(skill_id)
    left join public.player_skills_v3 as owned
      on owned.user_id = v_user_id and owned.skill_id = req.skill_id
  ) < (v_prerequisites -> 'total' ->> 'points')::integer then
    return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3',
      jsonb_build_object('ok', false, 'code', 'PREREQUISITE_REQUIRED'));
  end if;

  insert into public.player_skills_v3(user_id, skill_id, rank)
  values (v_user_id, p_skill_id, 1)
  on conflict (user_id, skill_id) do update
  set rank = public.player_skills_v3.rank + 1, updated_at = now();
  update public.player_core_v3
  set revision = revision + 1, updated_at = now() where user_id = v_user_id;
  v_response := jsonb_build_object('ok', true, 'code', 'OK',
    'snapshot', public.private_build_student_snapshot_v3(v_user_id));
  return public.private_store_receipt_v3(v_request_id, 'learn_student_skill_v3', v_response);
end;
$$;

revoke all on function public.enhance_student_weapon_v3(bigint, text) from public, anon;
revoke all on function public.choose_student_specialization_v3(text, bigint, text) from public, anon;
revoke all on function public.learn_student_skill_v3(text, bigint, text) from public, anon;
grant execute on function public.enhance_student_weapon_v3(bigint, text) to authenticated;
grant execute on function public.choose_student_specialization_v3(text, bigint, text) to authenticated;
grant execute on function public.learn_student_skill_v3(text, bigint, text) to authenticated;
