-- Phase 2: server-authoritative economy, equipment, and skills.

create table if not exists public.game_item_catalog_v3 (
  item_id text primary key check (char_length(item_id) between 1 and 80),
  inventory_kind text not null check (inventory_kind in ('gear', 'costume')),
  currency_kind text not null check (currency_kind in ('gold', 'building', 'none')),
  price integer not null check (price >= 0),
  slot text not null check (slot in ('weapon', 'head', 'armor', 'accessory')),
  class_name text check (class_name is null or class_name in ('warrior', 'mage', 'priest')),
  level_required integer not null check (level_required between 1 and 10),
  quest_only boolean not null default false
);

create table if not exists public.game_skill_catalog_v3 (
  skill_id text primary key check (char_length(skill_id) between 1 and 80),
  class_name text not null check (class_name in ('warrior', 'mage', 'priest')),
  spec_name text,
  unlock_level integer not null check (unlock_level between 1 and 10),
  max_rank integer not null check (max_rank between 1 and 20),
  point_cost integer not null check (point_cost between 1 and 20),
  prerequisites jsonb not null check (jsonb_typeof(prerequisites) = 'object')
);

create table if not exists public.game_specialization_catalog_v3 (
  class_name text not null check (class_name in ('warrior', 'mage', 'priest')),
  spec_name text not null,
  primary key (class_name, spec_name)
);

alter table public.game_item_catalog_v3 enable row level security;
alter table public.game_item_catalog_v3 force row level security;
alter table public.game_skill_catalog_v3 enable row level security;
alter table public.game_skill_catalog_v3 force row level security;
alter table public.game_specialization_catalog_v3 enable row level security;
alter table public.game_specialization_catalog_v3 force row level security;

revoke all on table public.game_item_catalog_v3 from public, anon, authenticated;
revoke all on table public.game_skill_catalog_v3 from public, anon, authenticated;
revoke all on table public.game_specialization_catalog_v3 from public, anon, authenticated;

alter table public.player_inventory_v3
  add column inventory_kind text not null default 'gear'
  check (inventory_kind in ('gear', 'costume'));
alter table public.player_inventory_v3
  drop constraint if exists player_inventory_v3_user_id_equipped_slot_key;
create unique index if not exists player_inventory_v3_kind_slot_uidx
  on public.player_inventory_v3(user_id, inventory_kind, equipped_slot)
  where equipped_slot is not null;
create unique index if not exists player_inventory_v3_kind_item_uidx
  on public.player_inventory_v3(user_id, inventory_kind, item_definition_id);

-- BEGIN GENERATED AUTHORITY CATALOG V3
-- Generated by tools/generate-authority-catalog-v3.mjs. Do not edit.
-- base-items: 40
-- costumes: 11
-- total-items: 51
-- skills: 42

insert into public.game_item_catalog_v3
  (item_id, inventory_kind, currency_kind, price, slot, class_name, level_required, quest_only)
values
('blueSword','gear','gold',70,'weapon','warrior',3,false),
('blueWizardHat','gear','gold',55,'head','mage',3,false),
('bronzeGreatsword','gear','gold',30,'weapon','warrior',1,false),
('cloverBadge','gear','building',5,'accessory',null,3,false),
('crimsonArmor','gear','gold',320,'armor','warrior',9,false),
('crimsonHelm','gear','gold',260,'head','warrior',9,false),
('crystalStaff','gear','gold',30,'weapon','mage',1,false),
('dawnTome','gear','gold',320,'weapon','priest',9,false),
('featherWing','gear','building',5,'accessory',null,3,false),
('forestCloak','gear','gold',30,'armor',null,1,false),
('goldCirclet','gear','gold',130,'head','priest',6,false),
('goldVestment','gear','gold',160,'armor','priest',6,false),
('guardAura','gear','building',5,'accessory',null,3,false),
('holyBook','gear','gold',30,'weapon','priest',1,false),
('honorCrown','gear','none',0,'head',null,1,true),
('ironSword','gear','gold',160,'weapon','warrior',6,false),
('ironwoodStaff','gear','gold',160,'weapon','mage',6,false),
('leatherArmor','gear','gold',70,'armor','warrior',3,false),
('leatherHelm','gear','gold',55,'head','warrior',3,false),
('mithrilStaff','gear','gold',320,'weapon','mage',9,false),
('mithrilSword','gear','gold',320,'weapon','warrior',9,false),
('navyRobe','gear','gold',160,'armor','mage',6,false),
('navyWizardHat','gear','gold',130,'head','mage',6,false),
('noviceHat','gear','gold',20,'head',null,1,false),
('oakStaff','gear','gold',70,'weapon','mage',3,false),
('prayerBook','gear','gold',70,'weapon','priest',3,false),
('roseHood','gear','gold',260,'head','priest',9,false),
('roseVestment','gear','gold',320,'armor','priest',9,false),
('silverBook','gear','gold',160,'weapon','priest',6,false),
('sixthWing','gear','building',5,'accessory',null,3,false),
('skyRobe','gear','gold',70,'armor','mage',3,false),
('starCape','gear','none',0,'armor',null,1,true),
('starPendant','gear','building',5,'accessory',null,3,false),
('steelArmor','gear','gold',160,'armor','warrior',6,false),
('steelHelm','gear','gold',130,'head','warrior',6,false),
('violetRobe','gear','gold',320,'armor','mage',9,false),
('violetWizardHat','gear','gold',260,'head','mage',9,false),
('whiteCloak','gear','none',0,'armor',null,1,true),
('whiteHood','gear','gold',55,'head','priest',3,false),
('whiteVestment','gear','gold',70,'armor','priest',3,false),
('cs_angelWing','costume','gold',380,'accessory',null,1,false),
('cs_bunnyBand','costume','gold',120,'head',null,1,false),
('cs_flowerCrown','costume','gold',260,'head',null,1,false),
('cs_peachDress','costume','gold',420,'armor',null,1,false),
('cs_questSproutRibbon','costume','none',0,'accessory',null,1,true),
('cs_rainbowAura','costume','gold',500,'accessory',null,1,false),
('cs_ribbon','costume','gold',100,'accessory',null,1,false),
('cs_sailorCape','costume','gold',150,'armor',null,1,false),
('cs_starCrown','costume','gold',480,'head',null,1,false),
('cs_starryRobe','costume','gold',320,'armor',null,1,false),
('cs_strangeWing','costume','gold',440,'accessory',null,1,false)
on conflict (item_id) do update set
  inventory_kind = excluded.inventory_kind, currency_kind = excluded.currency_kind,
  price = excluded.price, slot = excluded.slot, class_name = excluded.class_name,
  level_required = excluded.level_required, quest_only = excluded.quest_only;

insert into public.game_skill_catalog_v3
  (skill_id, class_name, spec_name, unlock_level, max_rank, point_cost, prerequisites)
values
('mage_basic_barrier','mage',null,1,1,1,'{"all":["mage_basic_bolt"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_basic_bolt','mage',null,1,1,1,'{"all":["mage_basic_element"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_basic_element','mage',null,1,5,1,'{"all":["mage_basic_mana"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_basic_mana','mage',null,1,5,1,'{"all":[],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fire_burst_v24','mage','화염',7,1,1,'{"all":["mage_fire_ember_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fire_ember_v24','mage','화염',7,5,1,'{"all":["mage_fireball_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fire_focus_v24','mage','화염',5,3,1,'{"all":["mage_basic_barrier"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fire_meteor_v24','mage','화염',9,1,1,'{"all":["mage_fire_burst_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_fireball_v24','mage','화염',5,1,1,'{"all":["mage_fire_focus_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_armor_v24','mage','냉기',7,1,1,'{"all":["mage_frost_lance_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_focus_v24','mage','냉기',5,3,1,'{"all":["mage_basic_barrier"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_lance_v24','mage','냉기',5,1,1,'{"all":["mage_frost_focus_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_mind_v24','mage','냉기',7,5,1,'{"all":["mage_frost_armor_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('mage_frost_storm_v24','mage','냉기',9,1,1,'{"all":["mage_frost_mind_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_basic_faith','priest',null,1,3,1,'{"all":[],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_basic_life','priest',null,1,5,1,'{"all":["priest_basic_faith"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_basic_prayer','priest',null,1,3,1,'{"all":["priest_basic_smite"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_basic_smite','priest',null,1,1,1,'{"all":["priest_basic_life"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_absorb_v24','priest','신성',5,1,1,'{"all":["priest_holy_focus_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_barrier_v24','priest','신성',7,1,1,'{"all":["priest_holy_absorb_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_focus_v24','priest','신성',5,5,1,'{"all":["priest_basic_prayer"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_grace_v24','priest','신성',7,3,1,'{"all":["priest_holy_barrier_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_holy_judgment_v24','priest','신성',9,1,1,'{"all":["priest_holy_grace_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_focus_v24','priest','암흑',5,5,1,'{"all":["priest_basic_prayer"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_judgment_v24','priest','암흑',9,1,1,'{"all":["priest_shadow_void_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_mark_v24','priest','암흑',7,1,1,'{"all":["priest_shadow_seed_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_seed_v24','priest','암흑',5,1,1,'{"all":["priest_shadow_focus_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('priest_shadow_void_v24','priest','암흑',7,5,1,'{"all":["priest_shadow_mark_v24"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_basic_blade','warrior',null,1,3,1,'{"all":["warrior_basic_body"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_basic_body','warrior',null,1,3,1,'{"all":[],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_basic_guard','warrior',null,1,3,1,'{"all":["warrior_basic_blade"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_basic_strike','warrior',null,1,1,1,'{"all":["warrior_basic_guard"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_armor','warrior','방어',5,5,1,'{"all":["warrior_def_stance"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_bastion','warrior','방어',9,1,1,'{"all":["warrior_def_wall"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_resist','warrior','방어',7,5,1,'{"all":["warrior_def_armor"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_stance','warrior','방어',5,1,1,'{"all":["warrior_basic_strike"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_def_wall','warrior','방어',7,1,1,'{"all":["warrior_def_resist"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_breaker','warrior','무기',7,3,1,'{"all":["warrior_weapon_rage"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_judgment','warrior','무기',9,1,1,'{"all":["warrior_weapon_breaker"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_mastery','warrior','무기',5,5,1,'{"all":["warrior_basic_strike"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_rage','warrior','무기',7,3,1,'{"all":["warrior_weapon_slash"],"ranks":{},"any":[],"total":null}'::jsonb),
('warrior_weapon_slash','warrior','무기',5,1,1,'{"all":["warrior_weapon_mastery"],"ranks":{},"any":[],"total":null}'::jsonb)
on conflict (skill_id) do update set
  class_name = excluded.class_name, spec_name = excluded.spec_name,
  unlock_level = excluded.unlock_level, max_rank = excluded.max_rank,
  point_cost = excluded.point_cost, prerequisites = excluded.prerequisites;

insert into public.game_specialization_catalog_v3(class_name, spec_name) values
('warrior','방어'),
('warrior','무기'),
('mage','냉기'),
('mage','화염'),
('priest','신성'),
('priest','암흑')
on conflict (class_name, spec_name) do nothing;
-- END GENERATED AUTHORITY CATALOG V3


alter function public.private_build_student_snapshot_v3(uuid)
  rename to private_build_student_snapshot_v3_phase1;

create or replace function public.private_build_student_snapshot_v3(
  p_user_id uuid
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when base.snapshot is null then null
    else jsonb_set(
      base.snapshot,
      '{inventory}',
      coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', i.id,
          'item_definition_id', i.item_definition_id,
          'inventory_kind', i.inventory_kind,
          'enhancement_tier', i.enhancement_tier,
          'equipped_slot', i.equipped_slot
        ) order by i.inventory_kind, i.item_definition_id, i.id)
        from public.player_inventory_v3 as i
        where i.user_id = p_user_id
      ), '[]'::jsonb)
    )
  end
  from (
    select public.private_build_student_snapshot_v3_phase1(p_user_id) as snapshot
  ) as base;
$$;

revoke all on function public.private_build_student_snapshot_v3_phase1(uuid)
  from public, anon, authenticated;
revoke all on function public.private_build_student_snapshot_v3(uuid)
  from public, anon, authenticated;
